# Generated by Django 5.2.6 on 2025-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_no', models.IntegerField()),
                ('colour', models.CharField(max_length=10)),
                ('product_no', models.IntegerField()),
                ('brand', models.CharField(max_length=10)),
                ('waranty', models.IntegerField()),
            ],
        ),
    ]
